import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'Eta-2 Actis',
  xws: 'eta2actis',
  size: 'Small',
  dial: [
    '1TW',
    '1YW',
    '2EP',
    '2TW',
    '2BB',
    '2FB',
    '2NB',
    '2YW',
    '2RP',
    '3TW',
    '3BB',
    '3FB',
    '3NB',
    '3YW',
    '4FB',
    '4KR',
    '5FW',
  ],
  faction: 'Galactic Republic',
  stats: [
    { type: 'attack', arc: 'Bullseye Arc', value: 3 },
    { type: 'attack', arc: 'Front Arc', value: 2 },
    { type: 'agility', value: 3 },
    { type: 'hull', value: 3 },
  ],
  actions: [
    { type: 'Focus', difficulty: 'White' },
    { type: 'Evade', difficulty: 'White' },
    { type: 'Lock', difficulty: 'Purple' },
    { type: 'Barrel Roll', difficulty: 'White' },
    { type: 'Boost', difficulty: 'White' },
  ],
  ability: {
    name: 'Intuitive Controls',
    text:
      'During the System Phase, you may perform a purple [Barrel Roll] or purple [Boost] action.',
  },
  pilots: [
    {
      xws: 'anakinskywalker-eta2actis',
      ffg: 781,
      name: 'Anakin Skywalker',
      cost: 6,
      loadout: 20,
      limited: 1,
      initiative: 6,
      caption: 'Hero of Coruscant',
      slots: [
        'Force Power',
        'Force Power',
        'Talent',
        'Cannon',
        'Astromech',
        'Modification',
      ],
      standard: true,
      force: { value: 3, recovers: 1, side: ['light', 'dark'] },
      epic: true,
      ability:
        'After you or a friendly Obi-Wan Kenobi ship at range 0-3 executes a maneuver, if there are more enemy ships than other friendly ships at range 0-1 of that ship, you may spend 1 [Force]. If you do, that ship removes 1 red token of your choice.',
      keywords: ['Dark Side', 'Jedi', 'Light Side'],
      extended: true,
    },
    {
      xws: 'obiwankenobi-eta2actis',
      ffg: 782,
      name: 'Obi-Wan Kenobi',
      cost: 5,
      loadout: 15,
      limited: 1,
      initiative: 5,
      caption: 'Guardian of Democracy',
      slots: ['Force Power', 'Talent', 'Cannon', 'Astromech', 'Modification'],
      force: { value: 3, recovers: 1, side: ['light'] },
      standard: true,
      epic: true,
      ability:
        'After you or a friendly Anakin Skywalker ship at range 0-3 executes a maneuver, if there are more enemy ships than other friendly ships at range 0-1 of that ship, you may spend 1 [Force]. If you do, that ship gains 1 focus token.',
      keywords: ['Jedi', 'Light Side'],
      extended: true,
    },
    {
      xws: 'aaylasecura',
      ffg: 783,
      name: 'Aayla Secura',
      cost: 5,
      limited: 1,
      initiative: 5,
      caption: 'Confident Warrior',
      slots: ['Force Power', 'Talent', 'Cannon', 'Astromech', 'Modification'],
      force: { value: 2, recovers: 1, side: ['light'] },
      standard: true,
      epic: true,
      ability:
        'While an enemy ship in your [Front Arc] at range 0-1 performs an attack, the defender may change 1 blank result to a [Focus] result.',
      keywords: ['Jedi', 'Light Side'],
      loadout: 15,
      extended: true,
    },
    {
      name: 'Shaak Ti',
      xws: 'shaakti',
      initiative: 4,
      limited: 1,
      caption: 'Compassionate Mentor',
      standard: true,
      force: { value: 2, recovers: 1, side: ['light'] },
      ability:
        'At the start of the End Phase, you may spend any number of [Force] to choose that many friendly ships at range 0-2. Each chosen ship does not remove 1 focus or evade token during this End Phase.',
      slots: ['Force Power', 'Talent', 'Cannon', 'Astromech', 'Modification'],
      cost: 5,
      epic: true,
      ffg: 784,
      keywords: ['Jedi', 'Light Side'],
      loadout: 18,
      extended: true,
    },
    {
      name: 'Jedi General',
      xws: 'jedigeneral',
      initiative: 4,
      limited: 0,
      text:
        'As the Clone Wars take their toll on the ranks of the Jedi Order, those that remain must assume even greater responsibilities in the Grand Army of the Republic.',
      standard: true,
      force: { value: 2, recovers: 1, side: ['light'] },
      slots: ['Force Power', 'Cannon', 'Astromech', 'Modification'],
      cost: 5,
      epic: true,
      ffg: 786,
      keywords: ['Jedi', 'Light Side'],
      loadout: 4,
      extended: true,
    },
    {
      name: 'Yoda',
      xws: 'yoda',
      initiative: 3,
      limited: 1,
      caption: 'Grand Master',
      standard: true,
      force: { value: 3, recovers: 1, side: ['light'] },
      ability:
        'After another friendly ship at range 0-3 spends 1 or more [Force], you may spend 1 [Force]. If you do, that ship recovers 1 [Force].',
      slots: [
        'Force Power',
        'Force Power',
        'Cannon',
        'Astromech',
        'Modification',
      ],
      cost: 5,
      epic: true,
      ffg: 785,
      keywords: ['Jedi', 'Light Side'],
      loadout: 16,
      extended: true,
    },
  ],
  ffg: 76,
  icon:
    'https://squadbuilder.fantasyflightgames.com/ship_types/I_Eta-2_Actis.png',
};

export default t;
