import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'V-19 Torrent Starfighter',
  xws: 'v19torrentstarfighter',
  size: 'Small',
  dial: [
    '1TR',
    '1BB',
    '1FB',
    '1NB',
    '1YR',
    '2ER',
    '2TW',
    '2BW',
    '2FB',
    '2NW',
    '2YW',
    '2RR',
    '3BR',
    '3FB',
    '3NR',
    '3KR',
    '4FW',
  ],
  faction: 'Galactic Republic',
  stats: [
    { type: 'attack', arc: 'Front Arc', value: 2 },
    { type: 'agility', value: 2 },
    { type: 'hull', value: 5 },
  ],
  actions: [
    { type: 'Focus', difficulty: 'White' },
    { type: 'Evade', difficulty: 'White' },
    { type: 'Lock', difficulty: 'White' },
    {
      type: 'Barrel Roll',
      difficulty: 'White',
      linked: { type: 'Evade', difficulty: 'Red' },
    },
  ],
  pilots: [
    {
      name: '“Kickback”',
      caption: 'Blue Four',
      xws: 'kickback',
      initiative: 4,
      limited: 1,
      ability:
        'After you perform a [Barrel Roll] action, you may perform a red [Lock] action.',
      standard: true,
      epic: true,
      cost: 5,
      slots: ['Talent', 'Talent', 'Missile', 'Missile', 'Modification'],
      ffg: 517,
      keywords: ['Clone'],
      loadout: 16,
      extended: true,
    },
    {
      name: '“Odd Ball”',
      caption: 'CC-2237',
      xws: 'oddball',
      initiative: 5,
      limited: 1,
      ability:
        'After you fully execute a red maneuver or perform a red action, if there is an enemy ship in your [Bullseye Arc], you may acquire a lock on that ship.',
      standard: true,
      epic: true,
      cost: 5,
      loadout: 16,
      slots: ['Talent', 'Torpedo', 'Missile', 'Modification', 'Modification'],
      ffg: 516,
      keywords: ['Clone'],
      extended: true,
    },
    {
      name: '“Swoop”',
      caption: 'Blue Six',
      xws: 'swoop',
      initiative: 3,
      limited: 1,
      ability:
        'After a friendly small or medium ship fully executes a speed 3-4 maneuver, if it is at range 0-1, it may perform a red [Boost] action.',
      standard: true,
      epic: true,
      cost: 4,
      slots: ['Talent', 'Missile', 'Missile', 'Modification'],
      ffg: 519,
      keywords: ['Clone'],
      loadout: 12,
      extended: true,
    },
    {
      name: '“Axe”',
      caption: 'Blue Two',
      xws: 'axe',
      initiative: 3,
      limited: 1,
      ability:
        'After you defend or perform an attack, you may choose a friendly ship at range 1-2 in your [Left Arc] or [Right Arc]. If you do, transfer 1 green token to that ship.',
      standard: true,
      epic: true,
      cost: 4,
      slots: ['Talent', 'Missile', 'Missile', 'Modification'],
      ffg: 518,
      keywords: ['Clone'],
      loadout: 12,
      extended: true,
    },
    {
      name: '“Tucker”',
      caption: 'Blue Five',
      xws: 'tucker',
      initiative: 2,
      limited: 1,
      ability:
        'After a friendly ship at range 1-2 performs an attack against an enemy ship in your [Front Arc], you may perform a [Focus] action.',
      standard: true,
      epic: true,
      cost: 4,
      slots: ['Talent', 'Missile', 'Missile', 'Modification'],
      ffg: 520,
      keywords: ['Clone'],
      loadout: 12,
      extended: true,
    },
    {
      name: 'Blue Squadron Protector',
      xws: 'bluesquadronprotector',
      initiative: 3,
      limited: 0,
      text:
        "Blue Squadron's elite clone pilots are trained to fly their V-19s in conjunction with Jedi and often support famous commanders such as Anakin Skywalker and Ahsoka Tano.",
      standard: true,
      epic: true,
      cost: 4,
      slots: ['Missile', 'Missile', 'Modification'],
      ffg: 521,
      keywords: ['Clone'],
      loadout: 10,
      extended: true,
    },
    {
      name: 'Gold Squadron Trooper',
      xws: 'goldsquadrontrooper',
      initiative: 2,
      limited: 0,
      text:
        'The V-19 Torrent starfighter was designed to be a light escort to nimble Delta-7 interceptors flown by Jedi Knights, and has a unique flight profile to reflect this role.',
      standard: true,
      epic: true,
      cost: 4,
      slots: ['Missile', 'Modification', 'Modification'],
      ffg: 522,
      keywords: ['Clone'],
      loadout: 10,
      extended: true,
    },
  ],
  ffg: 62,
  icon:
    'https://squadbuilder.fantasyflightgames.com/ship_types/I_V-19Torrent.png',
};

export default t;
