import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'MG-100 StarFortress',
  xws: 'mg100starfortress',
  ffg: 55,
  size: 'Large',
  dial: [
    '0OR',
    '1TR',
    '1BB',
    '1FB',
    '1NB',
    '1YR',
    '2TW',
    '2BW',
    '2FB',
    '2NW',
    '2YW',
    '3BR',
    '3FW',
    '3NR',
  ],
  faction: 'Resistance',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 3 },
    { arc: 'Double Turret Arc', type: 'attack', value: 2 },
    { type: 'agility', value: 1 },
    { type: 'hull', value: 9 },
    { type: 'shields', value: 3 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Lock' },
    { difficulty: 'White', type: 'Rotate Arc' },
    { difficulty: 'White', type: 'Reload' },
  ],
  icon:
    'https://infinitearenas.com/xw2/images/shipicons/resistance/I_StarFortress.png',
  pilots: [
    {
      name: 'Cobalt Squadron Bomber',
      initiative: 1,
      limited: 0,
      xws: 'cobaltsquadronbomber',
      text:
        'Whether the ordnance silos of their StarFortresses are loaded with proton bombs or relief supplies, the heroic crews of Cobalt Squadron dedicate their lives to making a difference in the galaxy.',
      cost: 6,
      slots: [
        'Sensor',
        'Tech',
        'Gunner',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      ffg: 434,
      standard: false,
      epic: true,
      loadout: 12,
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/pilots/cobaltsquadronbomber.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/cobaltsquadronbomber.png',
    },
    {
      name: 'Cat',
      caption: 'Cobalt Wasp',
      initiative: 1,
      limited: 1,
      xws: 'cat',
      ability:
        'While you perform a primary attack, if the defender is at range 0-1 of at least 1 friendly device, roll 1 additional die.',
      cost: 5,
      slots: [
        'Talent',
        'Sensor',
        'Tech',
        'Crew',
        'Gunner',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      ffg: 433,
      standard: false,
      epic: true,
      loadout: 17,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/cat.png',
      artwork: 'https://infinitearenas.com/xw2/images/artwork/pilots/cat.png',
    },
    {
      name: 'Vennie',
      caption: 'Crimson Cutter',
      initiative: 2,
      limited: 1,
      xws: 'vennie',
      ability:
        "While you defend, if the attacker is in a friendly ship's [Single Turret Arc], you may add 1 [Focus] result to your roll.",
      cost: 6,
      slots: [
        'Sensor',
        'Torpedo',
        'Crew',
        'Gunner',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      ffg: 448,
      standard: false,
      epic: true,
      loadout: 18,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/vennie.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/vennie.png',
    },
    {
      name: 'Ben Teene',
      caption: 'Crimson Bolide',
      initiative: 3,
      limited: 1,
      xws: 'benteene',
      ability:
        'After you perform an attack, if the defender is in your [Single Turret Arc], assign the Rattled condition to the defender.',
      cost: 5,
      conditions: ['rattled'],
      slots: [
        'Sensor',
        'Tech',
        'Tech',
        'Crew',
        'Gunner',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      ffg: 432,
      standard: false,
      epic: true,
      loadout: 19,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/benteene.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/benteene.png',
    },
    {
      name: 'Edon Kappehl',
      caption: 'Crimson Hailstorm',
      initiative: 3,
      limited: 1,
      xws: 'edonkappehl',
      ability:
        'After you fully execute a blue or white maneuver, if you have not dropped or launched a device this round, you may drop 1 device.',
      cost: 6,
      slots: [
        'Sensor',
        'Tech',
        'Cannon',
        'Crew',
        'Gunner',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      ffg: 447,
      standard: false,
      epic: true,
      loadout: 22,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/edonkappehl.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/edonkappehl.png',
    },
    {
      name: 'Finch Dallow',
      caption: 'Cobalt Hammer',
      initiative: 4,
      limited: 1,
      xws: 'finchdallow',
      ability:
        'Before you would drop a bomb, you may place it in the play area touching you instead.',
      cost: 6,
      slots: [
        'Sensor',
        'Tech',
        'Missile',
        'Crew',
        'Gunner',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      ffg: 431,
      standard: false,
      epic: true,
      loadout: 22,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/finchdallow.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/finchdallow.png',
    },
    {
      name: 'Paige Tico',
      caption: 'Hero',
      initiative: 5,
      limited: 1,
      xws: 'paigetico',
      ability:
        'After you drop a device, you may spend 1 [Charge] to drop an additional device.',
      cost: 6,
      charges: { value: 1, recovers: 1 },
      slots: [
        'Talent',
        'Sensor',
        'Tech',
        'Crew',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      standard: false,
      epic: true,
      ffg: 640,
      loadout: 23,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/paigetico.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/paigetico.png',
    },
  ],
};

export default t;
