import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'A/SF-01 B-wing',
  xws: 'asf01bwing',
  ffg: 17,
  size: 'Small',
  dial: [
    '1ER',
    '1TR',
    '1BB',
    '1FB',
    '1NB',
    '1YR',
    '1RR',
    '2TW',
    '2BW',
    '2FB',
    '2NW',
    '2YW',
    '2KR',
    '3BR',
    '3FB',
    '3NR',
    '4FR',
  ],
  faction: 'Rebel Alliance',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 3 },
    { type: 'agility', value: 1 },
    { type: 'hull', value: 4 },
    { type: 'shields', value: 4 },
  ],
  actions: [
    {
      difficulty: 'White',
      linked: { difficulty: 'Red', type: 'Barrel Roll' },
      type: 'Focus',
    },
    { difficulty: 'White', type: 'Lock' },
    { difficulty: 'White', type: 'Barrel Roll' },
  ],
  icon:
    'https://infinitearenas.com/xw2/images/shipicons/rebel-alliance/I_B-wing.png',
  pilots: [
    {
      name: 'Blade Squadron Veteran',
      initiative: 3,
      limited: 0,
      cost: 4,
      xws: 'bladesquadronveteran',
      text:
        "A unique gyrostabilization system surrounds the B-wing's cockpit, ensuring that the pilot always remains stationary during flight.",
      slots: ['Sensor', 'Cannon', 'Cannon', 'Torpedo', 'Configuration'],
      ffg: 25,
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      loadout: 4,
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/pilots/bladesquadronveteran.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/bladesquadronveteran.png',
    },
    {
      name: 'Blue Squadron Pilot',
      initiative: 2,
      limited: 0,
      cost: 4,
      xws: 'bluesquadronpilot',
      text:
        "Due to its heavy weapons array and resilient shielding, the B-wing has solidified itself as the Rebel Alliance's most innovative assault fighter.",
      slots: ['Sensor', 'Cannon', 'Cannon', 'Device', 'Configuration'],
      ffg: 26,
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      loadout: 4,
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/pilots/bluesquadronpilot.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/bluesquadronpilot.png',
    },
    {
      name: 'Braylen Stramm',
      caption: 'Blade Leader',
      initiative: 4,
      limited: 1,
      cost: 5,
      xws: 'braylenstramm',
      ability:
        'While you defend or perform an attack, if you are stressed, you may reroll up to 2 of your dice.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Torpedo',
        'Device',
        'Modification',
        'Configuration',
      ],
      ffg: 23,
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      loadout: 12,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/braylenstramm.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/braylenstramm.png',
    },
    {
      name: 'Ten Numb',
      caption: 'Blue Five',
      initiative: 4,
      limited: 1,
      cost: 5,
      xws: 'tennumb',
      ability:
        'While you defend or perform an attack, you may spend 1 stress token to change all of your [Focus] results to [Evade] or [Hit] results.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Torpedo',
        'Device',
        'Modification',
        'Configuration',
      ],
      ffg: 24,
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      loadout: 14,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/tennumb.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/tennumb.png',
    },
    {
      name: 'Gina Moonsong',
      caption: 'Insubordinate Ace',
      initiative: 5,
      limited: 1,
      cost: 4,
      xws: 'ginamoonsong',
      ability:
        'At the start of the Engagement Phase, you must transfer 1 of your stress tokens to another friendly ship at range 0-2.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Torpedo',
        'Device',
        'Modification',
        'Configuration',
      ],
      standard: true,
      epic: true,
      ffg: 628,
      keywords: ['B-wing'],
      loadout: 11,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/ginamoonsong.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/ginamoonsong.png',
    },
    {
      xws: 'herasyndulla-asf01bwing',
      name: 'Hera Syndulla',
      caption: 'Phoenix Leader',
      cost: 5,
      initiative: 6,
      limited: 1,
      ability:
        'While another friendly ship at range 1-2 defends or performs an attack, during a Modify Dice step, you may transfer 1 of your focus tokens, evade tokens, or locks to that ship.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Torpedo',
        'Missile',
        'Device',
        'Modification',
        'Title',
        'Configuration',
      ],
      standard: true,
      epic: true,
      ffg: 878,
      loadout: 14,
      extended: true,
      keywords: ['B-wing', 'Spectre'],
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/herasyndulla-asf01bwing.png',
      image:
        'https://infinitearenas.com/xw2/images/pilots/herasyndulla-asf01bwing.png',
    },
    {
      xws: 'netrempollard',
      name: 'Netrem Pollard',
      caption: 'Dagger Leader',
      cost: 4,
      initiative: 3,
      limited: 1,
      ability:
        'After you barrel roll, you may choose 1 friendly ship that is not stressed at range 0-1. That ship gains 1 stress token, then you rotate 180°.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Missile',
        'Device',
        'Modification',
        'Configuration',
      ],
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      ffg: 879,
      loadout: 10,
      extended: true,
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/netrempollard.png',
      image: 'https://infinitearenas.com/xw2/images/pilots/netrempollard.png',
    },
    {
      xws: 'adonfox',
      name: 'Adon Fox',
      caption: 'Battle over Endor',
      cost: 5,
      initiative: 1,
      limited: 1,
      ability: 'While you defend, if you are stressed, roll 1 additional die.',
      slots: [],
      shipAbility: {
        name: 'Gyro-Cockpit',
        text:
          "After you gain a stress token, you may spend 2 [Charge] to gain an evade token.\n\nWhen you drop a device, you may spend a [Charge] to set the template with its middle line aligned with the hashmark on your ship's left or right side instead of your rear guides",
      },
      charges: { value: 2, recovers: 1 },
      shipActions: [
        {
          difficulty: 'White',
          linked: { difficulty: 'Red', type: 'Barrel Roll' },
          type: 'Focus',
        },
        { difficulty: 'White', type: 'Lock' },
        {
          difficulty: 'White',
          type: 'Barrel Roll',
          linked: { difficulty: 'Red', type: 'Lock' },
        },
        { difficulty: 'Red', type: 'Reload' },
      ],
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      standardLoadout: [
        'itsatrap-battleoverendor',
        'partinggift-battleoverendor',
        'protonbombs',
        'protonrockets',
      ],
      extended: true,
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/adonfox-battleoverendor.png',
      image:
        'https://infinitearenas.com/xw2/images/pilots/adonfox-battleoverendor.png',
    },
    {
      xws: 'braylenstramm-battleoverendor',
      name: 'Braylen Stramm',
      caption: 'Battle over Endor',
      cost: 4,
      initiative: 4,
      limited: 1,
      ability:
        'At the start of the Engagement Phase, if a friendly <strong>Gina Moonsong</strong> ship at range 0-2 is stressed, you may gain a focus token.',
      slots: [],
      shipAbility: {
        name: 'Gyro-Cockpit',
        text:
          "After you gain a stress token, you may spend 2 [Charge] to gain an evade token.\n\nWhen you drop a device, you may spend a [Charge] to set the template with its middle line aligned with the hashmark on your ship's left or right side instead of your rear guides",
      },
      charges: { value: 2, recovers: 1 },
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 3 },
        { type: 'agility', value: 1 },
        { type: 'hull', value: 4 },
        { type: 'shields', value: 5 },
      ],
      shipActions: [
        {
          difficulty: 'White',
          linked: { difficulty: 'Red', type: 'Barrel Roll' },
          type: 'Focus',
        },
        { difficulty: 'White', type: 'Lock' },
        {
          difficulty: 'White',
          type: 'Barrel Roll',
          linked: { difficulty: 'Red', type: 'Lock' },
        },
        { difficulty: 'Red', type: 'Reload' },
      ],
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      standardLoadout: [
        'itsatrap-battleoverendor',
        'protonbombs',
        'homingmissiles',
        'delayedfuses',
      ],
      extended: true,
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/braylenstramm-battleoverendor.png',
      image:
        'https://infinitearenas.com/xw2/images/pilots/braylenstramm-battleoverendor.png',
    },
    {
      xws: 'ginamoonsong-battleoverendor',
      name: 'Gina Moonsong',
      caption: 'Battle over Endor',
      cost: 5,
      initiative: 5,
      limited: 1,
      ability:
        'At the start of the Engagement Phase, if a friendly <strong>Braylen Stramm</strong> ship at range 0-2 is stressed, you may acquire a lock.',
      slots: [],
      shipAbility: {
        name: 'Gyro-Cockpit',
        text:
          "After you gain a stress token, you may spend 2 [Charge] to gain an evade token.\n\nWhen you drop a device, you may spend a [Charge] to set the template with its middle line aligned with the hashmark on your ship's left or right side instead of your rear guides",
      },
      charges: { value: 2, recovers: 1 },
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 3 },
        { type: 'agility', value: 1 },
        { type: 'hull', value: 4 },
        { type: 'shields', value: 5 },
      ],
      shipActions: [
        {
          difficulty: 'White',
          linked: { difficulty: 'Red', type: 'Barrel Roll' },
          type: 'Focus',
        },
        { difficulty: 'White', type: 'Lock' },
        {
          difficulty: 'White',
          type: 'Barrel Roll',
          linked: { difficulty: 'Red', type: 'Lock' },
        },
        { difficulty: 'Red', type: 'Reload' },
      ],
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      standardLoadout: [
        'itsatrap-battleoverendor',
        'juke',
        'ionbombs',
        'protontorpedoes',
      ],
      extended: true,
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/ginamoonsong-battleoverendor.png',
      image:
        'https://infinitearenas.com/xw2/images/pilots/ginamoonsong-battleoverendor.png',
    },
  ],
};

export default t;
