import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'A/SF-01 B-wing',
  xws: 'asf01bwing',
  ffg: 17,
  size: 'Small',
  dial: [
    '1ER',
    '1TR',
    '1BB',
    '1FB',
    '1NB',
    '1YR',
    '1RR',
    '2TW',
    '2BW',
    '2FB',
    '2NW',
    '2YW',
    '2KR',
    '3BR',
    '3FB',
    '3NR',
    '4FR',
  ],
  faction: 'Rebel Alliance',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 3 },
    { type: 'agility', value: 1 },
    { type: 'hull', value: 4 },
    { type: 'shields', value: 4 },
  ],
  actions: [
    {
      difficulty: 'White',
      linked: { difficulty: 'Red', type: 'Barrel Roll' },
      type: 'Focus',
    },
    { difficulty: 'White', type: 'Lock' },
    { difficulty: 'White', type: 'Barrel Roll' },
  ],
  icon: 'https://squadbuilder.fantasyflightgames.com/ship_types/I_B-wing.png',
  pilots: [
    {
      name: 'Blade Squadron Veteran',
      initiative: 3,
      limited: 0,
      cost: 5,
      xws: 'bladesquadronveteran',
      text:
        "A unique gyrostabilization system surrounds the B-wing's cockpit, ensuring that the pilot always remains stationary during flight.",
      slots: ['Sensor', 'Cannon', 'Cannon', 'Torpedo', 'Configuration'],
      ffg: 25,
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      loadout: 6,
      extended: true,
    },
    {
      name: 'Blue Squadron Pilot',
      initiative: 2,
      limited: 0,
      cost: 5,
      xws: 'bluesquadronpilot',
      text:
        "Due to its heavy weapons array and resilient shielding, the B-wing has solidified itself as the Rebel Alliance's most innovative assault fighter.",
      slots: ['Sensor', 'Cannon', 'Cannon', 'Device', 'Configuration'],
      ffg: 26,
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      loadout: 6,
      extended: true,
    },
    {
      name: 'Braylen Stramm',
      caption: 'Blade Leader',
      initiative: 4,
      limited: 1,
      cost: 5,
      xws: 'braylenstramm',
      ability:
        'While you defend or perform an attack, if you are stressed, you may reroll up to 2 of your dice.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Torpedo',
        'Device',
        'Modification',
        'Configuration',
      ],
      ffg: 23,
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      loadout: 18,
      extended: true,
    },
    {
      name: 'Ten Numb',
      caption: 'Blue Five',
      initiative: 4,
      limited: 1,
      cost: 5,
      xws: 'tennumb',
      ability:
        'While you defend or perform an attack, you may spend 1 stress token to change all of your [Focus] results to [Evade] or [Hit] results.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Torpedo',
        'Device',
        'Modification',
        'Configuration',
      ],
      ffg: 24,
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      loadout: 20,
      extended: true,
    },
    {
      name: 'Gina Moonsong',
      caption: 'Insubordinate Ace',
      initiative: 5,
      limited: 1,
      cost: 4,
      xws: 'ginamoonsong',
      ability:
        'At the start of the Engagement Phase, you must transfer 1 of your stress tokens to another friendly ship at range 0-2.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Torpedo',
        'Device',
        'Modification',
        'Configuration',
      ],
      standard: true,
      epic: true,
      ffg: 628,
      keywords: ['B-wing'],
      loadout: 11,
      extended: true,
    },
    {
      xws: 'herasyndulla-asf01bwing',
      name: 'Hera Syndulla',
      caption: 'Phoenix Leader',
      cost: 6,
      initiative: 6,
      limited: 1,
      ability:
        'While another friendly ship at range 1-2 defends or performs an attack, during a Modify Dice step, you may transfer 1 of your focus tokens, evade tokens, or locks to that ship.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Torpedo',
        'Missile',
        'Device',
        'Modification',
        'Title',
        'Configuration',
      ],
      standard: true,
      epic: true,
      keywords: ['B-wing', 'Spectre'],
      ffg: 878,
      loadout: 27,
      extended: true,
    },
    {
      xws: 'netrempollard',
      name: 'Netrem Pollard',
      caption: 'Dagger Leader',
      cost: 4,
      initiative: 3,
      limited: 1,
      ability:
        'After you barrel roll, you may choose 1 friendly ship that is not stressed at range 0-1. That ship gains 1 stress token, then you rotate 180°.',
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Cannon',
        'Missile',
        'Device',
        'Modification',
        'Configuration',
      ],
      standard: true,
      epic: true,
      keywords: ['B-wing'],
      ffg: 879,
      loadout: 11,
      extended: true,
    },
  ],
};

export default t;
