import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'ARC-170 Starfighter',
  xws: 'arc170starfighter',
  ffg: 31,
  size: 'Medium',
  dial: [
    '1BB',
    '1FB',
    '1NB',
    '2TW',
    '2BB',
    '2FB',
    '2NB',
    '2YW',
    '3TR',
    '3BW',
    '3FW',
    '3NW',
    '3YR',
    '4FR',
    '4KR',
  ],
  faction: 'Rebel Alliance',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 3 },
    { arc: 'Rear Arc', type: 'attack', value: 2 },
    { type: 'agility', value: 1 },
    { type: 'hull', value: 6 },
    { type: 'shields', value: 3 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Lock' },
    { difficulty: 'Red', type: 'Barrel Roll' },
  ],
  icon: 'https://squadbuilder.fantasyflightgames.com/ship_types/I_Arc-170.png',
  pilots: [
    {
      name: 'Garven Dreis',
      caption: 'Red Leader',
      initiative: 4,
      limited: 1,
      cost: 5,
      xws: 'garvendreis',
      ability:
        'After you spend a focus token, you may choose 1 friendly ship at range 1-3. That ship gains 1 focus token.',
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Crew',
        'Crew',
        'Gunner',
        'Astromech',
        'Modification',
      ],
      ffg: 66,
      standard: true,
      epic: true,
      loadout: 11,
      extended: true,
      image:
        'https://squadbuilder.fantasyflightgames.com/card_images/Card_Pilot_66.png',
      artwork:
        'https://squadbuilder.fantasyflightgames.com/card_art/Card_art_XW_P_66.jpg',
    },
    {
      name: 'Ibtisam',
      caption: 'Survivor of Endor',
      initiative: 3,
      limited: 1,
      cost: 5,
      xws: 'ibtisam',
      ability:
        'After you fully execute a maneuver, if you are stressed, you may roll 1 attack die. On a [Hit] or [Critical Hit] result, remove 1 stress token.',
      slots: [
        'Talent',
        'Torpedo',
        'Crew',
        'Crew',
        'Gunner',
        'Astromech',
        'Modification',
      ],
      ffg: 68,
      standard: true,
      epic: true,
      loadout: 14,
      extended: true,
      image:
        'https://squadbuilder.fantasyflightgames.com/card_images/Card_Pilot_68.png',
      artwork:
        'https://squadbuilder.fantasyflightgames.com/card_art/Card_art_XW_P_68.jpg',
    },
    {
      name: 'Norra Wexley',
      caption: 'Gold Nine',
      initiative: 5,
      limited: 1,
      cost: 6,
      xws: 'norrawexley',
      ability:
        'While you defend, if there is an enemy ship at range 0-1, add 1 [Evade] result to your dice results.',
      slots: [
        'Talent',
        'Torpedo',
        'Crew',
        'Crew',
        'Gunner',
        'Astromech',
        'Modification',
      ],
      ffg: 65,
      standard: true,
      epic: true,
      loadout: 16,
      extended: true,
      image:
        'https://squadbuilder.fantasyflightgames.com/card_images/Card_Pilot_65.png',
      artwork:
        'https://squadbuilder.fantasyflightgames.com/card_art/Card_art_XW_P_65.jpg',
    },
    {
      name: 'Shara Bey',
      caption: 'Green Four',
      initiative: 4,
      limited: 1,
      cost: 5,
      xws: 'sharabey',
      ability:
        'While you defend or perform a primary attack, you may spend 1 lock you have on the enemy ship to add 1 [Focus] result to your dice results.',
      slots: [
        'Talent',
        'Torpedo',
        'Missile',
        'Crew',
        'Crew',
        'Gunner',
        'Astromech',
        'Modification',
      ],
      ffg: 67,
      standard: true,
      epic: true,
      loadout: 12,
      extended: true,
      image:
        'https://squadbuilder.fantasyflightgames.com/card_images/Card_Pilot_67.png',
      artwork:
        'https://squadbuilder.fantasyflightgames.com/card_art/Card_art_XW_P_67.jpg',
    },
  ],
};

export default t;
