import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'YV-666 Light Freighter',
  xws: 'yv666lightfreighter',
  ffg: 24,
  size: 'Large',
  dial: [
    '0OR',
    '1BB',
    '1FB',
    '1NB',
    '2TR',
    '2BW',
    '2FB',
    '2NW',
    '2YR',
    '3TW',
    '3BW',
    '3FB',
    '3NW',
    '3YW',
    '4FW',
  ],
  faction: 'Scum and Villainy',
  stats: [
    { arc: 'Full Front Arc', type: 'attack', value: 3 },
    { type: 'agility', value: 1 },
    { type: 'hull', value: 9 },
    { type: 'shields', value: 3 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Reinforce' },
    { difficulty: 'White', type: 'Lock' },
  ],
  icon: 'https://squadbuilder.fantasyflightgames.com/ship_types/I_YV-666.png',
  pilots: [
    {
      name: 'Bossk',
      caption: 'Fearsome Hunter',
      initiative: 4,
      limited: 1,
      cost: 7,
      xws: 'bossk',
      ability:
        'While you perform a primary attack, after the Neutralize Results step, you may spend 1 [Critical Hit] result to add 2 [Hit] results.',
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Crew',
        'Crew',
        'Gunner',
        'Illicit',
        'Modification',
        'Title',
      ],
      ffg: 210,
      standard: true,
      epic: true,
      loadout: 22,
      extended: true,
      keywords: ['Bounty Hunter', 'Freighter'],
      image:
        'https://squadbuilder.fantasyflightgames.com/card_images/Card_Pilot_210.png',
      artwork:
        'https://squadbuilder.fantasyflightgames.com/card_art/Card_art_XW_P_210.jpg',
    },
    {
      name: 'Latts Razzi',
      caption: 'Martial Artist',
      initiative: 3,
      limited: 1,
      cost: 6,
      xws: 'lattsrazzi',
      ability:
        'At the start of the Engagement Phase, you may choose a ship at range 1 and spend a lock you have on that ship. If you do, that ship gains 1 tractor token.',
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Crew',
        'Crew',
        'Gunner',
        'Illicit',
        'Modification',
        'Title',
      ],
      ffg: 212,
      standard: true,
      epic: true,
      loadout: 16,
      extended: true,
      keywords: ['Bounty Hunter', 'Freighter'],
      image:
        'https://squadbuilder.fantasyflightgames.com/card_images/Card_Pilot_212.png',
      artwork:
        'https://squadbuilder.fantasyflightgames.com/card_art/Card_art_XW_P_212.jpg',
    },
    {
      name: 'Moralo Eval',
      caption: 'Criminal Mastermind',
      initiative: 4,
      limited: 1,
      cost: 7,
      xws: 'moraloeval',
      ability:
        'If you would flee, you may spend 1 [Charge]. If you do, place yourself in reserves instead. At the start of the next Planning Phase, place yourself within range 1 of the edge of the play area that you fled from.',
      charges: { value: 2, recovers: 0 },
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Crew',
        'Crew',
        'Gunner',
        'Illicit',
        'Modification',
      ],
      ffg: 211,
      standard: true,
      epic: true,
      keywords: ['Freighter'],
      loadout: 20,
      extended: true,
      image:
        'https://squadbuilder.fantasyflightgames.com/card_images/Card_Pilot_211.png',
      artwork:
        'https://squadbuilder.fantasyflightgames.com/card_art/Card_art_XW_P_211.jpg',
    },
    {
      name: 'Trandoshan Slaver',
      initiative: 2,
      limited: 0,
      cost: 6,
      xws: 'trandoshanslaver',
      text:
        'The spacious triple-decker design of the YV-666 makes it popular among bounty hunters and slavers, who often retrofit an entire deck for prisoner transport.',
      slots: ['Cannon', 'Missile', 'Modification'],
      ffg: 213,
      standard: true,
      epic: true,
      keywords: ['Freighter'],
      loadout: 6,
      extended: true,
      image:
        'https://squadbuilder.fantasyflightgames.com/card_images/Card_Pilot_213.png',
      artwork:
        'https://squadbuilder.fantasyflightgames.com/card_art/Card_art_XW_P_213.jpg',
    },
  ],
};

export default t;
