const icons: { [s: string]: string } = {
  agility: '^',
  astromech: 'A',
  attack: '%',
  'bank left': '7',
  bankleft: '7',
  'bank right': '9',
  bankright: '9',
  'barrel roll': 'r',
  barrelroll: 'r',
  basesmall: 'Á',
  basemedium: 'Â',
  baselarge: 'Ã',
  boost: 'b',
  'bullseye arc': '}',
  bullseyearc: '}',
  calculate: 'a',
  cannon: 'C',
  cargo: 'G',
  charge: 'g',
  charges: 'g',
  cloak: 'k',
  command: 'V',
  'condition-outline': 'Æ',
  condition: '°',
  configuration: 'n',
  config: 'n',
  coordinate: 'o',
  crew: 'W',
  'critical hit': 'c',
  crit: 'c',
  'dalan-bankleft': '[',
  'dalan-bankright': ']',
  device: 'B',
  'double turret arc': 'q',
  doubleturretarc: 'q',
  'galactic empire': '@',
  galacticempire: '@',
  empire: '@',
  'galactic republic': '/',
  galacticrepublic: '/',
  energy: '(',
  epic: ')',
  evade: 'e',
  'first order': '+',
  firstorder: '+',
  focus: 'f',
  force: 'h',
  'force power': 'h',
  forcecharge: 'h',
  forcepower: 'F',
  'front arc': '{',
  frontarc: '{',
  'full front arc': '~',
  fullfrontarc: '~',
  'full rear arc': '¡',
  fullreararc: '¡',
  gunner: 'Y',
  hardpoint: 'H',
  'helmet-imperial': 'y',
  'helmet-rebel': 'x',
  'helmet-scum': 'z',
  hit: 'd',
  hull: '&',
  'ig88d-sloopleft': '"',
  'ig88d-sloopright': "'",
  illicit: 'I',
  jam: 'j',
  'koiogran turn': '2',
  kturn: '2',
  leftarc: '£',
  'left arc': '£',
  linked: '>',
  missile: 'M',
  modification: 'm',
  'obstacle-core2asteroid0-outline': '\u0109',
  'obstacle-core2asteroid0': '\u0125',
  'obstacle-core2asteroid1-outline': '\u010c',
  'obstacle-core2asteroid1': '\u0128',
  'obstacle-core2asteroid2-outline': '\u010a',
  'obstacle-core2asteroid2': '\u0126',
  'obstacle-core2asteroid3-outline': '\u010b',
  'obstacle-core2asteroid3': '\u0127',
  'obstacle-core2asteroid4-outline': '\u010d',
  'obstacle-core2asteroid4': '\u0129',
  'obstacle-core2asteroid5-outline': '\u010e',
  'obstacle-core2asteroid5': '\u012a',
  'obstacle-coreasteroid0-outline': '\u0102',
  'obstacle-coreasteroid0': '\u011e',
  'obstacle-coreasteroid1-outline': '\u0103',
  'obstacle-coreasteroid1': '\u011f',
  'obstacle-coreasteroid2-outline': '\u0101',
  'obstacle-coreasteroid2': '\u011d',
  'obstacle-coreasteroid3-outline': '\u0105',
  'obstacle-coreasteroid3': '\u0121',
  'obstacle-coreasteroid4-outline': '\u0104',
  'obstacle-coreasteroid4': '\u0120',
  'obstacle-coreasteroid5-outline': '\u0100',
  'obstacle-coreasteroid5': '\u011c',
  'obstacle-vt49decimatordebris0-outline': '\u0110',
  'obstacle-vt49decimatordebris0': '\u012c',
  'obstacle-vt49decimatordebris1-outline': '\u0111',
  'obstacle-vt49decimatordebris1': '\u012d',
  'obstacle-vt49decimatordebris2-outline': '\u0107',
  'obstacle-vt49decimatordebris2': '\u0123',
  'obstacle-yt2400debris0-outline': '\u010f',
  'obstacle-yt2400debris0': '\u012b',
  'obstacle-yt2400debris1-outline': '\u0108',
  'obstacle-yt2400debris1': '\u0124',
  'obstacle-yt2400debris2-outline': '\u0106',
  'obstacle-yt2400debris2': '\u0122',
  'obstacle-gascloud1': '\u012e',
  'obstacle-gascloud1-outline': '\u0112',
  'obstacle-gascloud2': '\u012f',
  'obstacle-gascloud2-outline': '\u0113',
  'obstacle-gascloud3': '\u0130',
  'obstacle-gascloud3-outline': '\u0114',
  'obstacle-gascloud4': '\u0131',
  'obstacle-gascloud4-outline': '\u0115',
  'obstacle-gascloud5': '\u0132',
  'obstacle-gascloud5-outline': '\u0116',
  'obstacle-gascloud6': '\u0133',
  'obstacle-gascloud6-outline': '\u0117',
  ordnance: '?',
  rangebonusindicator: '?',
  'rear arc': '|',
  reararc: '|',
  'rebel-outline': '-',
  resistance: '!',
  'rebel alliance': '!',
  rebelalliance: '!',
  rebel: '!',
  recover: 'v',
  recurring: '`',
  doublerecurring: '_',
  reinforce: 'i',
  reload: '=',
  reversebankleft: 'J',
  reversebankright: 'L',
  reversestraight: 'K',
  rightarc: '¢',
  'right arc': '¢',
  'rotate arc': 'R',
  rotatearc: 'R',
  'scum and villainy': '#',
  scumandvillainy: '#',
  scum: '#',
  shields: '*',
  shield: '*',
  'single turret arc': 'p',
  singleturretarc: 'p',
  slam: 's',
  "segnor's loop left": '1',
  sloopleft: '1',
  "segnor's loop right": '3',
  sloopright: '3',
  'separatist alliance': '.',
  separatistalliance: '.',
  'squad-point-cost': '0',
  stationary: '5',
  stop: '5',
  straight: '8',
  sensor: 'S',
  talent: 'E',
  lock: 'l',
  'tactical relay': 'Z',
  tacticalrelay: 'Z',
  targetlock: 'l',
  team: 'T',
  tech: 'X',
  title: 't',
  'token-cannotattack-outline': 'í',
  'token-cannotattack': 'Ö',
  'token-crit-outline': 'è',
  'token-crit': 'Ç',
  'token-evade-outline': 'é',
  'token-evade': 'Å',
  'token-focus-outline': 'ç',
  'token-focus': 'Ä',
  torpedo: 'P',
  'tallon roll left': ':',
  trollleft: ':',
  'tallon roll right': ';',
  trollright: ';',
  'turn left': '4',
  turnleft: '4',
  'turn right': '6',
  turnright: '6',
  turret: 'U',
  'unique-outline': '•',
  unique: 'u',
};

export const xwingIcons = (icon?: string) => {
  if (!icon) {
    return;
  }
  return icons[icon.toLowerCase()] || '0';
};

const shipMap: { [s: string]: string } = {
  aggressorassaultfighter: 'i',
  alphaclassstarwing: '&',
  arc170starfighter: 'c',
  attackshuttle: 'g',
  auzituckgunship: '@',
  rz1awing: 'a',
  rz2awing: 'a',
  asf01bwing: 'b',
  mg100starfortress: 'Z',
  cr90corelliancorvette: '2',
  croccruiser: '5',
  ewing: 'e',
  escapecraft: 'X',
  fireball: '0',
  firesprayclasspatrolcraft: 'f',
  g1astarfighter: 'n',
  gozanticlasscruiser: '4',
  gr75mediumtransport: '1',
  hwk290lightfreighter: 'h',
  ig2000: 'i',
  jumpmaster5000: 'p',
  kihraxzfighter: 'r',
  btls8kwing: 'k',
  m12lkimogilafighter: 'K',
  lambdaclasst4ashuttle: 'l',
  lancerclasspursuitcraft: 'L',
  m3ainterceptor: 's',
  fangfighter: 'M',
  quadrijettransferspacetug: 'q',
  raiderclasscorvette: '3',
  scurrgh6bomber: 'H',
  sheathipedeclassshuttle: '%',
  starviperclassattackplatform: 'v',
  t70xwing: 'w',
  tieadvancedx1: 'A',
  tieadvancedv1: 'R',
  tieadvprototype: 'R',
  tieagaggressor: '`',
  tiesabomber: 'B',
  tieddefender: 'D',
  modifiedtielnfighter: 'F',
  tiebainterceptor: 'j',
  tielnfighter: 'F',
  tiefofighter: 'O',
  tieininterceptor: 'I',
  tiephphantom: 'P',
  tiecapunisher: 'N',
  tierbheavy: 'J',
  tiereaper: 'V',
  tiesffighter: 'S',
  tievnsilencer: '$',
  tieskstriker: 'T',
  upsilonclassshuttle: 'U',
  ut60duwing: 'u',
  vcx100lightfreighter: 'G',
  vt49decimator: 'd',
  t65xwing: 'x',
  scavengedyt1300: 'm',
  customizedyt1300lightfreighter: 'm',
  modifiedyt1300lightfreighter: 'm',
  yt2400: 'o',
  yt2400lightfreighter: 'o',
  yv666lightfreighter: 't',
  btla4ywing: 'y',
  z95af4headhunter: 'z',
  belbullab22starfighter: '[',
  vultureclassdroidfighter: '_',
  sithinfiltrator: ']',
  delta7aethersprite: '\\',
  v19torrentstarfighter: '^',
  nabooroyaln1starfighter: '<',
  hyenaclassdroidbomber: '=',
  resistancetransport: '>',
  resistancetransportpod: '?',
  nantexclassstarfighter: ';',
  btlbywing: ':',
  xiclasslightshuttle: 'Q',
  laatigunship: '/',
  hmpdroidgunship: '.',
  eta2actis: '-',
  nimbusclassvwing: ',',
  droidtrifighter: '+',
  syliureclasshyperspacering: '*',
};

export const shipIcons = (name: string) => {
  if (!name) {
    return;
  }
  const value = shipMap[name.toLowerCase()];
  if (!value) {
    console.info('MISSING ICON', name);
  }
  return value;
};
