import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'TIE/D Defender',
  xws: 'tieddefender',
  ffg: 18,
  size: 'Small',
  dial: [
    '1TR',
    '1BB',
    '1NB',
    '1YR',
    '2TR',
    '2BW',
    '2FB',
    '2NW',
    '2YR',
    '2KR',
    '3TW',
    '3BW',
    '3FB',
    '3NW',
    '3YW',
    '4FB',
    '4KW',
    '5FB',
  ],
  faction: 'Galactic Empire',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 3 },
    { type: 'agility', value: 3 },
    { type: 'hull', value: 3 },
    { type: 'shields', value: 4 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Evade' },
    { difficulty: 'White', type: 'Lock' },
    { difficulty: 'White', type: 'Barrel Roll' },
    { difficulty: 'White', type: 'Boost' },
  ],
  ability: {
    name: 'Full Throttle',
    text:
      'After you fully execute a speed 3-5 maneuver, you may perform an [Evade] action.',
  },
  icon:
    'https://squadbuilder.fantasyflightgames.com/ship_types/I_TIEDefender.png',
  pilots: [
    {
      name: 'Colonel Vessery',
      caption: 'Contemplative Commander',
      initiative: 4,
      limited: 1,
      cost: 7,
      xws: 'colonelvessery',
      ability:
        'While you perform an attack against a locked ship, after you roll attack dice, you may acquire a lock on the defender.',
      slots: ['Talent', 'Sensor', 'Cannon', 'Missile', 'Configuration'],
      ffg: 123,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 10,
      extended: true,
    },
    {
      name: 'Countess Ryad',
      caption: 'Cutthroat Politico',
      initiative: 4,
      limited: 1,
      cost: 7,
      xws: 'countessryad',
      ability:
        'While you would execute a [Straight] maneuver, you may increase the difficulty of the maneuver. If you do, execute it as a [Koiogran Turn] maneuver instead.',
      slots: [
        'Talent',
        'Sensor',
        'Sensor',
        'Cannon',
        'Missile',
        'Configuration',
      ],
      ffg: 124,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 12,
      extended: true,
    },
    {
      name: 'Delta Squadron Pilot',
      initiative: 1,
      limited: 0,
      cost: 7,
      xws: 'deltasquadronpilot',
      text:
        'In addition to its missile launchers and six wingtip laser cannons, the formidable TIE defender is equipped with deflector shields and a hyperdrive.',
      slots: ['Sensor', 'Cannon', 'Configuration'],
      ffg: 126,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 4,
      extended: true,
    },
    {
      name: 'Onyx Squadron Ace',
      initiative: 4,
      limited: 0,
      cost: 7,
      xws: 'onyxsquadronace',
      text:
        'The experimental TIE defender outclasses all other contemporary starfighters, though its size, speed, and array of weapons come at a tremendous cost in credits.',
      slots: ['Talent', 'Sensor', 'Cannon', 'Missile', 'Configuration'],
      ffg: 125,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 6,
      extended: true,
    },
    {
      name: 'Rexler Brath',
      caption: 'Onyx Leader',
      initiative: 5,
      limited: 1,
      cost: 7,
      xws: 'rexlerbrath',
      ability:
        "After you perform an attack that hits, if you are evading, expose 1 of the defender's damage cards.",
      slots: [
        'Talent',
        'Sensor',
        'Cannon',
        'Missile',
        'Missile',
        'Configuration',
      ],
      ffg: 122,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 13,
      extended: true,
    },
    {
      xws: 'vultskerris',
      name: 'Vult Skerris',
      caption: 'Arrogant Ace',
      cost: 7,
      initiative: 5,
      limited: 1,
      ability:
        'Action: Gain 1 strain token to recover 1 [Charge]. Before you engage, you may spend 1 [Charge] to perform an action.',
      slots: [
        'Talent',
        'Talent',
        'Sensor',
        'Cannon',
        'Missile',
        'Configuration',
      ],
      standard: true,
      epic: true,
      keywords: ['TIE'],
      ffg: 887,
      loadout: 13,
      extended: true,
    },
    {
      xws: 'darthvader-tieddefender',
      name: 'Darth Vader',
      caption: 'Dark Lord of the Sith',
      cost: 9,
      initiative: 6,
      limited: 1,
      ability:
        'You cannot spend [Force] except while attacking. While you perform an attack, you may spend 1 [Force] to change 1 blank result to a [Hit] result.',
      force: { value: 3, recovers: 1, side: ['dark'] },
      slots: [
        'Force Power',
        'Talent',
        'Tech',
        'Cannon',
        'Missile',
        'Configuration',
      ],
      standard: true,
      epic: true,
      keywords: ['Dark Side', 'Sith', 'TIE'],
      ffg: 886,
      loadout: 14,
      extended: true,
    },
    {
      xws: 'captaindobbs',
      name: 'Captain Dobbs',
      caption: 'Reliable Replacement',
      cost: 7,
      initiative: 3,
      limited: 1,
      ability:
        'While another friendly ship at range 0-1 defends, before the Neutralize Results step, if you are in the attack arc and are not ionized, you may gain 1 ion token to cancel 1 [Hit] result.',
      slots: ['Talent', 'Sensor', 'Cannon', 'Missile', 'Configuration'],
      standard: true,
      epic: true,
      keywords: ['TIE'],
      ffg: 888,
      loadout: 15,
      extended: true,
    },
  ],
};

export default t;
