import { Source } from '../../types';

export const t: Source[] = [
  {
    ffg: 1,
    xws: 'xwingsecondeditioncoreset',
    name: 'X-Wing Second Edition Core Set',
    wave: 0,
    released: true,
    contents: {
      ships: { t65xwing: 1, tielnfighter: 2 },
      pilots: {
        lukeskywalker: 1,
        jekporkins: 1,
        redsquadronveteran: 1,
        bluesquadronescort: 1,
        idenversio: 1,
        valenrudor: 1,
        blacksquadronace: 2,
        nightbeast: 1,
        obsidiansquadronpilot: 2,
        academypilot: 2,
      },
      upgrades: {
        elusive: 1,
        outmaneuver: 1,
        predator: 1,
        heightenedperception: 2,
        instinctiveaim: 1,
        sense: 2,
        supernaturalreflexes: 2,
        protontorpedoes: 1,
        r2astromech: 1,
        r2d2: 1,
        r3astromech: 1,
        r5astromech: 1,
        r5d8: 1,
        servomotorsfoils: 1,
        afterburners: 1,
        hullupgrade: 1,
        shieldupgrade: 1,
      },
    },
    sku: 'SWZ01',
  },
  {
    ffg: 48,
    xws: 'nevertellmetheoddsobstaclepack',
    name: 'Never Tell Me the Odds Obstacle Pack',
    wave: 6,
    released: true,
    contents: {
      ships: {},
      pilots: {},
      upgrades: { riggedcargochute: 1, protonbombs: 1, sparepartscanisters: 1 },
    },
  },
  {
    ffg: 49,
    xws: 'fullyloadeddevicespack',
    name: 'Fully Loaded Devices Pack',
    wave: 6,
    released: true,
    contents: {
      ships: {},
      pilots: {},
      upgrades: {
        clustermines: 1,
        trajectorysimulator: 1,
        seismiccharges: 1,
        ionbombs: 1,
        bombletgenerator: 1,
        connernets: 1,
        proximitymines: 1,
        electroprotonbomb: 1,
        delayedfuses: 2,
        protonbombs: 1,
      },
    },
  },
  {
    ffg: 50,
    xws: 'hotshotsandacesreinforcementpack',
    name: 'Hotshots and Aces Reinforcement Pack',
    wave: 6,
    released: true,
    contents: {
      ships: {},
      pilots: {
        bossk: 1,
        vagabond: 1,
        zizitlo: 1,
        g4rg0rvm: 1,
        lieutenantlehuse: 1,
        ginamoonsong: 1,
        k2so: 1,
        alexsandrkallus: 1,
        fifthbrother: 1,
        mornakee: 1,
        paigetico: 1,
        captainphasma: 1,
        rush: 1,
        leiaorgana: 1,
        nomlumb: 1,
        ronithblario: 1,
        'bossk-z95af4headhunter': 1,
        g4rgorvm: 1,
      },
      upgrades: {
        '000': 1,
        maul: 1,
        bt1: 1,
        composure: 2,
        agilegunner: 2,
        primedthrusters: 2,
        moldycrow: 1,
        predictiveshot: 2,
        barragerockets: 2,
        hate: 2,
        advancedoptics: 2,
        patternanalyzer: 2,
        brilliantevasion: 2,
        passivesensors: 2,
        autoblasters: 2,
        diamondboronmissiles: 1,
        plasmatorpedoes: 2,
        angleddeflectors: 2,
        snapshot: 2,
        foresight: 2,
        precognitivereflexes: 2,
        targetingcomputer: 3,
        k2so: 1,
        stabilizedsfoils: 2,
        magpulsewarheads: 2,
        coaxiumhyperfuel: 2,
      },
    },
  },
  {
    ffg: 50,
    xws: 'prideofmandalorereinforcementspack',
    name: 'Pride of Mandalore Reinforcements Pack',
    wave: 6,
    released: true,
    contents: {
      ships: {},
      pilots: {
        'fennrau-rebel-fang': 1,
        mandalorianroyalguard: 2,
        isbjingoist: 2,
        moffgideon: 1,
        bodicavenj: 1,
        clanwrenvolunteer: 2,
      },
      upgrades: {
        'ahsokatano-crew': 1,
        primeministeralmec: 1,
        bokatankryze: 1,
        'bokatankryze-rebel-scum': 1,
        'maul-crew': 1,
        previzsla: 1,
        rookkast: 1,
        savageopress: 1,
        talmerrik: 1,
        sabinewren: 1,
        captainhark: 1,
        'fennrau-crew': 1,
        garsaxon: 1,
        korkiekryze: 1,
        obiwankenobi: 1,
        satinekryze: 1,
        tristanwren: 1,
        ursawren: 1,
        beskarreinforcedplating: 3,
        mandalorianoptics: 3,
        clantraining: 1,
        deadeyeshot: 1,
        ionlimiteroverride: 1,
        margsablclosure: 1,
        compassion: 1,
        malice: 1,
        blazerbomb: 1,
        concussionbombs: 1,
        thermaldetonators: 1,
        falsefriend: 1,
        suppressivegunner: 2,
        tibersaxon: 1,
        'ursawren-gunner': 1,
        weaponssystemsofficer: 2,
        falsetranspondercodes: 1,
        overtunedmodulators: 1,
      },
    },
  },
  {
    ffg: -1,
    xws: 'gauntletfighterexpansionpack',
    name: 'Gauntlet Fighter Expansion Pack',
    wave: 11,
    released: true,
    contents: {
      ships: { gauntletfighter: 1 },
      pilots: {
        maul: 1,
        rookkast: 1,
        shadowcollectiveoperator: 1,
        bokatankryze: 1,
        niteowlliberator: 1,
        'bokatankryze-separatistalliance': 1,
        previzsla: 1,
        deathwatchwarrior: 1,
        'ezrabridger-gauntletfighter': 1,
        'chopper-gauntletfighter': 1,
        mandalorianresistancepilot: 1,
        captainhark: 1,
        garsaxon: 1,
        imperialsupercommando: 1,
      },
      upgrades: {
        clanwrencommandos: 1,
        imperialsupercommandos: 1,
        niteowlcommandos: 1,
        deathwatchcommandos: 1,
        mandaloriansupercommandos: 1,
        enduring: 1,
        swivelwing: 1,
        nightbrother: 1,
        gauntlet: 1,
        dropseatbay: 1,
        combatboardingtube: 1,
        shatteringshot: 1,
        veterantailgunner: 1,
        overtunedmodulators: 1,
        blazerbomb: 2,
        concussionbombs: 2,
      },
    },
  },
  {
    ffg: -1,
    xws: 'rogueclassstarfighter',
    name: 'Rogue-class Starfighter Expansion Pack',
    wave: 11,
    released: true,
    contents: {
      ships: { rogueclassstarfighter: 2 },
      pilots: {
        'cadbane-separatistalliance': 1,
        ig101: 1,
        ig102: 1,
        ig111: 1,
        magnaguardexecutioner: 1,
        magnaguardprotector: 1,
        cadbane: 1,
        'viktorhel-rogueclassstarfighter': 1,
        'nomlumb-rogueclassstarfighter': 1,
        outerrimhunter: 1,
      },
      upgrades: {
        freelanceslicer: 1,
        ioncannon: 1,
        protoncannons: 2,
        syncedlasercannons: 2,
        trackingfob: 1,
        overtunedmodulators: 1,
        independentcalculations: 1,
        blazerbomb: 1,
        enduring: 2,
        notorius: 2,
        xanadublood: 1,
      },
    },
  },
  {
    ffg: -1,
    xws: 'hotshotsandacesiireinforcementpack',
    name: 'Hotshots and Aces || Reinforcements Pack',
    wave: 10,
    released: true,
    contents: {
      ships: {},
      pilots: {
        adigallia: 1,
        'adigallia-delta7baethersprite': 1,
        sicko: 1,
        kitfisto: 1,
        slammer: 1,
        gavynsykes: 1,
        volandas: 1,
        aurrasing: 1,
        durge: 1,
        theironassembler: 1,
        kelrodoaiholdout: 1,
        'corranhorn-t65xwing': 1,
        wesjanson: 1,
        tychocelchu: 1,
        keovenzee: 1,
        'popskrail-battleofyavin': 1,
        flightleaderubbel: 1,
        junoeclipse: 1,
        secondsister: 1,
        magnatolvan: 1,
        yricaquell: 1,
        hondoohnaka: 1,
        torphun: 1,
        'durge-separatistalliance': 1,
        doctoraphra: 1,
        lapin: 1,
        'poedameron-scavengedyt1300': 1,
        'landocalrissian-scavengedyt1300': 1,
        venisadoza: 1,
        zayversio: 1,
        takajamoreesa: 1,
        lieutenantgalek: 1,
        juljerjerrod: 1,
        dt798: 1,
        lingaava: 1,
        agenttierny: 1,
      },
      upgrades: {},
    },
  },
];

export default t;
