import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'Firespray-class Patrol Craft',
  xws: 'firesprayclasspatrolcraft',
  size: 'Medium',
  dial: [
    '1TW',
    '1BB',
    '1FB',
    '1NB',
    '1YW',
    '2TW',
    '2BW',
    '2FB',
    '2NW',
    '2YW',
    '3ER',
    '3BW',
    '3FB',
    '3NW',
    '3RR',
    '4FW',
    '4KR',
  ],
  faction: 'Separatist Alliance',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 3 },
    { arc: 'Rear Arc', type: 'attack', value: 3 },
    { type: 'agility', value: 2 },
    { type: 'hull', value: 6 },
    { type: 'shields', value: 4 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Lock' },
    { difficulty: 'Red', type: 'Reinforce' },
    { difficulty: 'White', type: 'Boost' },
  ],
  icon:
    'https://squadbuilder.fantasyflightgames.com/ship_types/I_FIrespray.png',
  pilots: [
    {
      name: 'Jango Fett',
      caption: 'Simple Man',
      initiative: 6,
      limited: 1,
      xws: 'jangofett',
      ability:
        "While you defend or perform a primary attack, if the difficulty of your revealed maneuver is less than that of the enemy ship's, you may change 1 of the enemy ship's [Focus] results to a blank result.",
      standard: true,
      epic: true,
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Crew',
        'Device',
        'Illicit',
        'Illicit',
        'Modification',
        'Title',
      ],
      cost: 9,
      ffg: 800,
      keywords: ['Bounty Hunter'],
      loadout: 27,
      extended: true,
    },
    {
      xws: 'zamwesell',
      name: 'Zam Wesell',
      caption: 'Clawdite Changeling',
      cost: 10,
      initiative: 5,
      limited: 1,
      ability:
        'Setup: Lose 2 [Charge]. During the System Phase, you may assign 1 of your secret conditions to yourself facedown: "You Should Thank Me" or "You\'d Better Mean Business"',
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Crew',
        'Device',
        'Illicit',
        'Modification',
        'Title',
      ],
      conditions: ['youdbettermeanbusiness', 'youshouldthankme'],
      standard: true,
      epic: true,
      ffg: 801,
      keywords: ['Bounty Hunter'],
      loadout: 22,
      extended: true,
    },
    {
      xws: 'bobafett-separatistalliance',
      ffg: 802,
      name: 'Boba Fett',
      cost: 7,
      limited: 1,
      initiative: 3,
      caption: 'Survivor',
      slots: [
        'Cannon',
        'Missile',
        'Crew',
        'Device',
        'Illicit',
        'Modification',
        'Title',
      ],
      standard: true,
      epic: true,
      ability:
        'While you defend, if there are no other friendly ships at range 0-2, you may change 1 of your blank results to a [Focus] result.',
      keywords: ['Bounty Hunter'],
      loadout: 16,
      extended: true,
    },
    {
      name: 'Separatist Racketeer',
      xws: 'separatistracketeer',
      initiative: 2,
      limited: 0,
      text:
        'Emboldened by the bitter stalemate of the Outer Rim Sieges, mercenary groups across the galaxy take the opportunity to profit from the ongoing war.',
      standard: true,
      slots: ['Cannon', 'Missile', 'Device'],
      cost: 7,
      epic: true,
      ffg: 803,
      loadout: 7,
      extended: true,
      caption: '',
    },
  ],
  ffg: 10,
};

export default t;
