import { ShipType } from '../../../types';

const t: ShipType = {
  name: { en: 'TIE/se Bomber' },
  xws: 'tiesebomber',
  size: 'Small',
  ffg: 87,
  dial: [
    '1TR',
    '1BW',
    '1FB',
    '1NW',
    '1YR',
    '2TW',
    '2BW',
    '2FB',
    '2NW',
    '2YW',
    '3LR',
    '3TW',
    '3BW',
    '3FB',
    '3NW',
    '3YW',
    '3PR',
    '4FW',
  ],
  faction: 'First Order',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 2 },
    { type: 'agility', value: 2 },
    { type: 'hull', value: 4 },
    { type: 'shields', value: 2 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Lock' },
    {
      difficulty: 'White',
      linked: { difficulty: 'Red', type: 'Lock' },
      type: 'Barrel Roll',
    },
    { difficulty: 'Red', type: 'Boost' },
    {
      difficulty: 'White',
      linked: { difficulty: 'Red', type: 'Evade' },
      type: 'Reload',
    },
  ],
  ability: {
    name: { en: 'Pursuit Thrusters' },
    text: { en: 'During the System Phase, you may perform a [Boost] action' },
  },
  icon: '???',
  pilots: [
    {
      name: { en: 'Breach' },
      xws: 'breach',
      initiative: 5,
      limited: 1,
      hyperspace: true,
      cost: 36,
      slots: [
        'Talent',
        'Tech',
        'Torpedo',
        'Missile',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      ability: {
        en:
          'After you fully execute a maneuver or perform a [Boost] action, if you moved through an enemy ship, you may acquire a lock on that ship.',
      },
      ffg: -999,
      artwork: '???',
      caption: { en: 'Ordnance Expert' },
      keywords: ['TIE'],
      epic: true,
      image: { en: '???' },
    },
    {
      name: { en: 'Scorch' },
      xws: 'scorch-tiesebomber',
      initiative: 4,
      limited: 1,
      hyperspace: true,
      cost: 35,
      slots: [
        'Talent',
        'Tech',
        'Torpedo',
        'Missile',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      ability: {
        en:
          'While a friendly ship at range 0-1 performs a primary attack, it may spend 1 [Hit] result. If it does, after defending, the defender gains 1 strain token.',
      },
      ffg: -999,
      artwork: '???',
      caption: { en: 'Jad Bean' },
      keywords: ['TIE'],
      epic: true,
      image: { en: '???' },
    },
    {
      name: { en: 'Dread' },
      xws: 'dread',
      initiative: 3,
      limited: 1,
      hyperspace: true,
      cost: 32,
      slots: [
        'Tech',
        'Torpedo',
        'Missile',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      text: { en: '???' },
      ffg: -999,
      artwork: '???',
      keywords: ['TIE'],
      epic: true,
      image: { en: '???' },
      caption: { en: 'Devotee of Devastation' },
      ability: {
        en:
          'After you reload, each ship in your [Bullseye Arc] gains 1 deplete token.',
      },
    },
    {
      name: { en: 'Grudge' },
      xws: 'grudge',
      initiative: 2,
      limited: 1,
      hyperspace: true,
      cost: 36,
      slots: [
        'Tech',
        'Torpedo',
        'Missile',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      ability: {
        en:
          'While a friendly bomb or mine at range 0-2 detonates, each time attack dice are rolled to resolve its effect, you may reroll up to 1 of those dice.',
      },
      ffg: -999,
      artwork: '???',
      caption: { en: 'Hateful Harrier' },
      keywords: ['TIE'],
      epic: true,
      image: { en: '???' },
    },
    {
      name: { en: 'First Order Cadet' },
      xws: 'firstordercadet',
      initiative: 3,
      limited: 0,
      hyperspace: true,
      cost: 32,
      slots: [
        'Talent',
        'Tech',
        'Torpedo',
        'Missile',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      text: {
        en:
          'The live-fire exercises of the First Order are intended to root out the weak, enforcing the maxim that only the strong survive.',
      },
      ffg: -999,
      artwork: '???',
      keywords: ['TIE'],
      epic: true,
      image: { en: '???' },
    },
    {
      name: { en: 'Sienar-Jaemus Test Pilot' },
      xws: 'sienarjaemustestpilot',
      initiative: 2,
      limited: 0,
      hyperspace: true,
      cost: 31,
      slots: [
        'Tech',
        'Torpedo',
        'Missile',
        'Gunner',
        'Device',
        'Device',
        'Modification',
      ],
      text: {
        en:
          'Equipped with four laser cannons and advanced systems, the TIE/se bomber is a remarkably maneuverable craft that brings devastating ordnance to bear against any who dare to stand against the First Order.',
      },
      ffg: -999,
      artwork: '???',
      keywords: ['TIE'],
      epic: true,
      image: { en: '???' },
    },
  ],
};

export default t;
