import { ShipType } from '../../../types';

const t: ShipType = {
  name: 'Upsilon-class Shuttle',
  xws: 'upsilonclassshuttle',
  ffg: 51,
  size: 'Large',
  dial: [
    '0OR',
    '1TR',
    '1BW',
    '1FB',
    '1NW',
    '1YR',
    '2TW',
    '2BB',
    '2FB',
    '2NB',
    '2YW',
    '3TR',
    '3BW',
    '3FW',
    '3NW',
    '3YR',
  ],
  faction: 'First Order',
  stats: [
    { type: 'attack', value: 4, arc: 'Front Arc' },
    { type: 'agility', value: 1 },
    { type: 'hull', value: 6 },
    { type: 'shields', value: 6 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Lock' },
    { difficulty: 'White', type: 'Reinforce' },
    { difficulty: 'White', type: 'Coordinate' },
    { difficulty: 'White', type: 'Jam' },
  ],
  ability: {
    name: 'Linked Battery',
    text: 'While you perform a [Cannon] attack, roll 1 additional die.',
  },
  icon: 'https://sb-cdn.fantasyflightgames.com/ship_types/I_UpsilonShuttle.png',
  pilots: [
    {
      name: 'Lieutenant Dormitz',
      caption: 'Hypercomms Specialist',
      initiative: 2,
      limited: 1,
      cost: 9,
      xws: 'lieutenantdormitz',
      ability:
        'Setup: After you are placed, friendly small ships can be placed anywhere in the play area at range 0-2 of you.',
      slots: [
        'Sensor',
        'Sensor',
        'Tech',
        'Tech',
        'Cannon',
        'Crew',
        'Crew',
        'Crew',
        'Modification',
      ],
      ffg: 412,
      standard: false,
      epic: true,
      loadout: 20,
      extended: true,
    },
    {
      name: 'Major Stridan',
      caption: 'Stentorian Commander',
      initiative: 4,
      limited: 1,
      cost: 7,
      xws: 'majorstridan',
      ability:
        'While you coordinate or resolve the effect of one of your upgrades, you may treat friendly ships at range 2-3 as being at range 0 or range 1.',
      slots: [
        'Sensor',
        'Tech',
        'Tech',
        'Cannon',
        'Crew',
        'Crew',
        'Crew',
        'Modification',
      ],
      ffg: 410,
      standard: false,
      epic: true,
      loadout: 13,
      extended: true,
    },
    {
      name: 'Petty Officer Thanisson',
      xws: 'pettyofficerthanisson',
      caption: 'Alert Flight Controller',
      initiative: 1,
      limited: 1,
      cost: 7,
      charges: { value: 1, recovers: 1 },
      ability:
        'During the Activation or Engagement Phase, after a ship in your [Front Arc] at range 0-2 gains 1 stress token, you may spend 1 [Charge]. If you do, that ship gains 1 tractor token.',
      slots: [
        'Sensor',
        'Tech',
        'Tech',
        'Cannon',
        'Cannon',
        'Crew',
        'Crew',
        'Crew',
        'Modification',
      ],
      ffg: 458,
      standard: false,
      epic: true,
      loadout: 14,
      extended: true,
    },
    {
      name: 'Starkiller Base Pilot',
      xws: 'starkillerbasepilot',
      initiative: 2,
      limited: 0,
      cost: 7,
      text:
        "The Upsilon-class command shuttle serves as a base of operations for many of the First Order's senior officers and agents. Its powerful sensors and communications equipment allow them to orchestrate the spread of terror across the galaxy.",
      slots: [
        'Sensor',
        'Tech',
        'Tech',
        'Cannon',
        'Crew',
        'Crew',
        'Modification',
      ],
      ffg: 413,
      standard: false,
      epic: true,
      loadout: 8,
      extended: true,
    },
    {
      name: 'Lieutenant Tavson',
      caption: 'Obedient Shuttle Pilot',
      initiative: 3,
      limited: 1,
      cost: 8,
      xws: 'lieutenanttavson',
      ability:
        'After you suffer damage, you may spend 1 [Charge] to perform an action.',
      charges: { value: 2, recovers: 1 },
      slots: [
        'Sensor',
        'Tech',
        'Tech',
        'Cannon',
        'Crew',
        'Crew',
        'Modification',
      ],
      ffg: 411,
      standard: false,
      epic: true,
      loadout: 15,
      extended: true,
    },
    {
      name: 'Captain Cardinal',
      caption: 'Principled Instructor',
      initiative: 4,
      limited: 1,
      cost: 7,
      xws: 'captaincardinal',
      ability:
        'While a friendly ship at range 1-2 with lower initiative than you defends or performs an attack, if you have at least 1 [Charge], that ship may reroll 1 [Focus] result. After an enemy ship at range 0-3 is destroyed, lose 1 [Charge].',
      charges: { value: 2, recovers: 0 },
      slots: [
        'Talent',
        'Sensor',
        'Tech',
        'Tech',
        'Cannon',
        'Crew',
        'Crew',
        'Crew',
        'Modification',
      ],
      ffg: 457,
      standard: false,
      epic: true,
      loadout: 12,
      extended: true,
    },
  ],
};

export default t;
